# Logging
logging.level.root=ERROR
logging.level.org.springframework.web=ERROR
logging.level.ch.kochse.tools.asyncapi.codegen=WARN
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss } [%thread] %-5level %logger{36} - %msg%n
logging.file.path=./log
logging.file.append=false
#
# Application Config
CodeGen.Message.ParentClass=ch.kochse.lib.common.messaging.base.AMessage
CodeGen.DTO.ParentInterface=ch.kochse.lib.common.messaging.base.IDTO
CodeGen.Enum.ParentInterface=ch.kochse.lib.common.messaging.base.IEnum
CodeGen.MessageType.ParentInterface=ch.kochse.lib.common.messaging.base.IMessageType
#
CodeGen.BasePackage=ch.kochse.hobby.garden.api
CodeGen.Message.Package=contract.msg
CodeGen.DTO.Package=contract.dto
CodeGen.Enum.Package=contract
CodeGen.Contract.Package=contract
CodeGen.Default.OutputDir=./build/generated/asyncapi/src/main/java
CodeGen.DateType=java.time.LocalDateTime

